import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import type { PropsWithChildren } from '@/types/common';
import '../css/globals.css';
import getIntl from '@/app/utils/getIntl';
import type { LocaleCode } from '@/types/i18n';
import ServerIntlProvider from '@/contexts/ServerIntlProvider';
import Navigation from '@/components/Navigation';
import AuthProvider from '@/contexts/AuthProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type Props = {
  params: { localeCode: LocaleCode };
};

async function RootLayout({ params, children }: PropsWithChildren<Props>) {
  const { messages, locale } = await getIntl(params.localeCode);

  return (
    <html lang="en">
      <ServerIntlProvider messages={messages} locale={locale}>
        <AuthProvider>
          <body className={inter.className}>
            <main>
              <Navigation localeCode={params.localeCode} />
              {children}
            </main>
          </body>
        </AuthProvider>
      </ServerIntlProvider>
    </html>
  );
}

export default RootLayout;
