import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import type { ServerComponentProps, PropsWithChildren } from '@/types/common';
import '../css/globals.css';
import getIntl from '@/app/utils/getIntl';
import ServerIntlProvider from '@/contexts/ServerIntlProvider';
import Navigation from '@/components/Navigation';
import AuthProvider from '@/contexts/AuthProvider';
import ConfirmationProvider from '@/contexts/ConfirmationProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

async function RootLayout({ params, children }: PropsWithChildren<ServerComponentProps>) {
  const { messages, locale } = await getIntl(params.locale);

  return (
    <html lang="en">
      <ServerIntlProvider messages={messages} locale={locale}>
        <AuthProvider>
          <body className={inter.className}>
            <ConfirmationProvider>
              <Navigation locale={locale} />
              <main>{children}</main>
            </ConfirmationProvider>
          </body>
        </AuthProvider>
      </ServerIntlProvider>
    </html>
  );
}

export default RootLayout;
